/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import javax.swing.JOptionPane;
import modelo.Empresa;
import modelo.EmpresaDAO;

/**
 *
 * @author SKAPIR
 */
public class EmpresaForm extends javax.swing.JPanel {

    /**
     * Creates new form EmpresaForm
     */
    public EmpresaForm() {
        initComponents();
        cargarDatosEmpresa();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnGuardarEmpresa = new javax.swing.JButton();
        txtNombre = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtRuc = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtRazonSocial = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        lblDireccion = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblRazonSocial = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        lblRuc = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnGuardarEmpresa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGuardarEmpresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/GuardarTodo.png"))); // NOI18N
        btnGuardarEmpresa.setText("GUARDAR");
        btnGuardarEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarEmpresaActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardarEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 410, 140, 40));
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(339, 182, 263, 33));
        jPanel1.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(647, 182, 217, 33));
        jPanel1.add(txtRuc, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 182, 253, 33));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setText("DATOS DE LA EMPRESA");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 40, 552, 54));
        jPanel1.add(txtRazonSocial, new org.netbeans.lib.awtextra.AbsoluteConstraints(339, 309, 253, 33));
        jPanel1.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 309, 253, 33));

        lblDireccion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblDireccion.setText("DIRECCION");
        jPanel1.add(lblDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 266, -1, -1));

        lblNombre.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNombre.setText("NOMBRE");
        jPanel1.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(339, 139, -1, -1));

        lblRazonSocial.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblRazonSocial.setText("RAZON SOCIAL");
        jPanel1.add(lblRazonSocial, new org.netbeans.lib.awtextra.AbsoluteConstraints(339, 266, -1, -1));

        lblTelefono.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTelefono.setText("TELEFONO");
        jPanel1.add(lblTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(647, 139, -1, -1));

        lblRuc.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblRuc.setText("RUC");
        jPanel1.add(lblRuc, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 145, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 990, 510));
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarEmpresaActionPerformed
        // TODO add your handling code here:
    EmpresaDAO dao = new EmpresaDAO();
    Empresa empresa = new Empresa();

    empresa.setRuc(txtRuc.getText());
    empresa.setNombre(txtNombre.getText());
    empresa.setTelefono(txtTelefono.getText());
    empresa.setDireccion(txtDireccion.getText());
    empresa.setRazonSocial(txtRazonSocial.getText());

    if (dao.guardarEmpresa(empresa)) {
        JOptionPane.showMessageDialog(this, "✅ Datos guardados correctamente.");
    } else {
        JOptionPane.showMessageDialog(this, "❌ Error al guardar los datos.");
    }
    }//GEN-LAST:event_btnGuardarEmpresaActionPerformed
private void cargarDatosEmpresa() {
    EmpresaDAO dao = new EmpresaDAO();
    Empresa e = dao.obtenerEmpresa();
    if (e != null) {
        txtRuc.setText(e.getRuc());
        txtNombre.setText(e.getNombre());
        txtTelefono.setText(e.getTelefono());
        txtDireccion.setText(e.getDireccion());
        txtRazonSocial.setText(e.getRazonSocial());
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardarEmpresa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblRazonSocial;
    private javax.swing.JLabel lblRuc;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtRazonSocial;
    private javax.swing.JTextField txtRuc;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
